### ISSUE TITLE
unable to read service

### ISSUE THREAD

**Issue by Bonfra04** [jonathantribouharet/flutter_cast#1]
onServiceResolved unable to read service: <MDNSService>...

with all of my devices.. what can i do?

**Comment by jonathantribouharet** [comment]
Hi,
can you show the exact line?
It should have the content of the DNS record, I've only test my code with the Chromecast Ultra.
This error should happen only if the device doesn't have a IP address.

**Comment by hansolowireless** [comment]
The log message is: 

W/MDNSPlugin( 1261): startDiscovery: enableUpdating is currently ignored on the Android platform
I/flutter ( 1261): [CastDiscoveryService] onServiceResolved unable to read service: <MDNSService>{ name='Chromecast-23ba7366e31eaee2bd30609390825d0e' serviceType='_googlecast._tcp.' host='10.0.0.16:8009' }

**Comment by Bonfra04** [comment]
I/flutter (14811): [CastDiscoveryService] onServiceResolved unable to read service: <MDNSService>{ name='MIBOX4-2ea453a630805807c0f1f743ca70672a' serviceType='_googlecast._tcp.' host='192.168.1.140:8009' bs='FA8FE3725B4A' ca='200709' cd='B9FE3D150F3B95D1C09C4EAD35B8553F' fn='MachineTV' ic='/setup/icon.png' id='2ea453a630805807c0f1f743ca70672a' md='MIBOX4' nf='1' rm='7DC4009FD782A6A5' rs='null' st='0' ve='05' }

same message on mibox and google home mini

**Comment by jonathantribouharet** [comment]
I will release a fix tomorrow.

**Comment by Bonfra04** [comment]
awsome

**Comment by jonathantribouharet** [comment]
Can you try with the 0.2.0 version I just released, it should work.

**Comment by Bonfra04** [comment]
It works perfectly.  Thanks!
