### ISSUE TITLE
startDiscovery: enableUpdating is currently ignored on the Android platform

### ISSUE THREAD

**Issue by Rohan2998** [jonathantribouharet/flutter_cast#10]
Hello guys, 

I need a feature to cast my app on TV so i am using this package. However **when i run the example code it gives me an error i specified in the title**. Can you kindly suggest what can be done to resolve this error.

Your help is much appreciated!

Regards,
Rohan

**Comment by jonathantribouharet** [comment]
This is not an error, just a warning #9
