### ISSUE TITLE
Android - entry.value must not be null in SuccessObject

### ISSUE THREAD

**Issue by carlosmuvi** [jonathantribouharet/flutter_cast#14]
First of all, thanks for the lib! 

I'm getting this crash when discovering devices. Seems to be an issue with `Bonsoir`, the native casting lib being used.
 
```
E/AndroidRuntime( 6015): Process: XXX, PID: 6015
E/AndroidRuntime( 6015): java.lang.IllegalStateException: entry.value must not be null
E/AndroidRuntime( 6015): 	at fr.skyost.bonsoir.SuccessObject.getAttributes(SuccessObject.kt:62)
E/AndroidRuntime( 6015): 	at fr.skyost.bonsoir.SuccessObject.serviceToJson(SuccessObject.kt:44)
E/AndroidRuntime( 6015): 	at fr.skyost.bonsoir.SuccessObject.toJson(SuccessObject.kt:25)
E/AndroidRuntime( 6015): 	at fr.skyost.bonsoir.discovery.BonsoirDiscoveryListener$onServiceResolved$1.run(BonsoirDiscoveryListener.kt:138)
E/AndroidRuntime( 6015): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 6015): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 6015): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 6015): 	at android.app.ActivityThread.main(ActivityThread.java:7660)
E/AndroidRuntime( 6015): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6015): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 6015): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by jonathantribouharet** [comment]
Hi,
you should post report this bug in [bonsoir repository](https://github.com/Skyost/Bonsoir) and maybe give more info / code.

**Comment by jonathantribouharet** [comment]
https://github.com/Skyost/Bonsoir/issues/17

**Comment by tinder-carlosvillar** [comment]
Sorry forgot to mention I already did, they already fixed it - https://github.com/Skyost/Bonsoir/issues/17

**Comment by t-kietzmann** [comment]
It seems that Bonsoir is updated, will be an update for this package soon?

**Comment by natebgurutech** [comment]
I'm still getting that error as well, it looks like they closed the issue

@jonathantribouharet any ideas?  Also, thanks for working on this, it's an awesome library =)

**Comment by natebgurutech** [comment]
Actually, a little digging later, it looks like they may have a fix:

this mentions the issue
https://github.com/Skyost/Bonsoir/issues/18

and has this PR ready to go
https://github.com/Skyost/Bonsoir/pull/19

**Comment by tleluc** [comment]
Hi, @jonathantribouharet @natebgurutech PR has been merged
Nice Sunday !

**Comment by jonathantribouharet** [comment]
Thanks, so you just need to update to the next version of bonsoir (or use the master branch for now).

**Comment by natebgurutech** [comment]
Nice!  I'll give it a try later today

**Comment by vanlooverenkoen** [comment]
For those looking I created a fork that uses the master branch.

-> https://github.com/vanlooverenkoen/flutter_cast/tree/bugfix/bonsoir-master

**Comment by t-kietzmann** [comment]
FYI:

fatal: Could not read from remote repository

Please make sure you have the correct access rights


and the repository exists.
exit code: 128
