### ISSUE TITLE
App crash on Android

### ISSUE THREAD

**Issue by t-kietzmann** [jonathantribouharet/flutter_cast#15]
Using Flutter 2.2.1 and Dart 2.12 (cast 1.1.0) i get this Message when running the Example code and the app crashes:

D/bonsoir ( 1865): [47211] Bonsoir discovery started : _googlecast._tcp
D/bonsoir ( 1865): [47211] Bonsoir has found a service : name: Chromecast-1eb02ca8afb99457c94b4f1a791887cf, type: _googlecast._tcp., host: null, port: 0, txtRecord:
D/bonsoir ( 1865): [47211] Bonsoir has resolved a service : name: Chromecast-1eb02ca8afb99457c94b4f1a791887cf, type: ._googlecast._tcp, host: /192.168.178.207, port: 8009, txtRecord: bs=FA8FCA396DE4	ca=200709#cd=815B2DDCB9FE3A397533DA599A9581C7
D/AndroidRuntime( 1865): Shutting down VM
E/AndroidRuntime( 1865): FATAL EXCEPTION: main
E/AndroidRuntime( 1865): Process: com.casttest.casttest, PID: 1865
E/AndroidRuntime( 1865): java.lang.IllegalStateException: entry.value must not be null
E/AndroidRuntime( 1865): 	at fr.skyost.bonsoir.SuccessObject.getAttributes(SuccessObject.kt:62)
E/AndroidRuntime( 1865): 	at fr.skyost.bonsoir.SuccessObject.serviceToJson(SuccessObject.kt:44)
E/AndroidRuntime( 1865): 	at fr.skyost.bonsoir.SuccessObject.toJson(SuccessObject.kt:25)
E/AndroidRuntime( 1865): 	at fr.skyost.bonsoir.discovery.BonsoirDiscoveryListener$onServiceResolved$1.run(BonsoirDiscoveryListener.kt:138)
E/AndroidRuntime( 1865): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 1865): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1865): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 1865): 	at android.app.ActivityThread.main(ActivityThread.java:7660)
E/AndroidRuntime( 1865): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 1865): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 1865): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

Someone an idea?
Thanks for support and the package! Keep on

**Comment by jonathantribouharet** [comment]
https://github.com/jonathantribouharet/flutter_cast/issues/14

**Comment by jonathantribouharet** [comment]
https://github.com/Skyost/Bonsoir/issues/17
