### ISSUE TITLE
Package Documentation

### ISSUE THREAD

**Issue by t-kietzmann** [jonathantribouharet/flutter_cast#16]
Hey there, at first many thanks for the package.

Where can i find a working Documentation? https://docs.rs/crate/gcast/0.1.5 isn't available.
Such for things like different messages (showing an image, etc.).

Thanks.

**Comment by jonathantribouharet** [comment]
Hi,
Everything is in the README, this library only allow to to communicate / send message with **your** application, so nothing about showing an image.
