### ISSUE TITLE
Reconnect

### ISSUE THREAD

**Issue by Eke** [jonathantribouharet/flutter_cast#18]
Hello, is there a way to reconnect to session afters is being close automatically by Chromecast?

**Comment by Eke** [comment]
Figured it out. If somebody will be interested, here is the correct flow:

After first connection and application launch you will get `RECEIVER_STATUS` message, find `sessionId` there and store it. Also store session object which is returned by calling: 

```
final session = await CastSession.connect(sessID, device);
```

When application will go to background call: 

```
Future _closeSession() async {
    final oldSessionId = currentSession.value?.sessionId;
    if (oldSessionId == null) {
      return Future.value();
    }

    await currentSession.value?.socket.flush();
    await currentSession.value?.socket.close();
    return Future.value();
  }
```

Don't call `CastSessionManager.closeSession` as it will kill Chromecast application too.

When Application will enter foreground just call: 

```
Future<bool> connectToDevice(
    CastDevice device, {
    String? sessionId,
    bool launch: true,
    bool getStatus = false,
  }) async {
    try {
      final sessID = sessionId ?? recieverStatus.value.sessionId;
      final session = await CastSession.connect(sessID, device);
      Action(() {
        currentSession.value = session;
        currentDevice.value = device;
      })();

      _startListeners(session);

      if (launch) {
        _sendMessage(
          namespace: CastSession.kNamespaceReceiver,
          type: _kTypeLaunch,
          includeMediaSessionId: false,
          payload: {'appId': '13413F7C'},
        );
      }

      if (getStatus) {
        _sendMessage(
          namespace: CastSession.kNamespaceReceiver,
          type: _kTypeGetStatus,
          payload: {},
        );
      }
      return Future.value(true);
    } catch (_) {
      return Future.value(false);
    }
  }
```

It's important to set `launch` to `false` and `getStatus` to `true`

**Comment by vanlooverenkoen** [comment]
Thanks for your samples.

Regarding the `CastSessionManager.closeSession` I don't have this method. I am trying to completly close my connection with the receiver app but it is not working. My chromecast app won't quite after using `CastSessionManager.endSession`
Do you have idea?

**Comment by Eke** [comment]
@vanlooverenkoen  you can call `close` method on current session (if you have stored reference to it).

Also make sure that socket connection is alive and has not timed out. If it's not alive, first you need to reconnect before requesting session close.

Also, you can try to send message to Chromecast:

```
sendMessage(CastSession.kNamespaceConnection, {
        'type': 'CLOSE',
      });
```

**Comment by vanlooverenkoen** [comment]
Aah you are using the connection namespace. I am using the receiver one. I will try that one first. All the other suggestions I have already done.

**Comment by vanlooverenkoen** [comment]
Caling `.close()` already does that. It is the STOP command that is not working I think. Because my application stays active on my chromecast.

**Comment by cogier** [comment]
I'm trying something similar. After starting a chromecast and closing my app, the cast continues playing. I would like to automatically reconnect to the cast when reopening the app.
Does this solution allow the user to reconnect to the cast and regain control?
