### ISSUE TITLE
Device discovery not working on Android?

### ISSUE THREAD

**Issue by hansolowireless** [jonathantribouharet/flutter_cast#2]
Thanks for sharing this plugin!

I am trying to implement it on Android, but the startDiscovery() method gives this message:

_enableUpdating is currently ignored on the Android platform_

And the app does not seem to detect the Chromecast. On iOS it's working fine.

I don't know if that message has to do with not finding devices or I am doing something else wrong.

**Comment by jonathantribouharet** [comment]
The discovery part use the plugin https://pub.dev/packages/mdns_plugin and there is a note about Android, I think the message "enableUpdating is currently ignored on the Android platform" is just about this note.

If your code work with iOS it should also work on Android.
I don't have a chromecast with me today.

**Comment by hansolowireless** [comment]
Actually on a physical device I am receiving the message in issue #1, so closing this one and following that one. Thanks!

**Comment by jonathantribouharet** [comment]
Can you send the detail log message in #1 .
