### ISSUE TITLE
Cast issue with "java.lang.IllegalStateException: entry.value must not be null"

### ISSUE THREAD

**Issue by SirBepy** [jonathantribouharet/flutter_cast#23]
Hi!

I tried to make a brand new project and add the one line (dependency) in the pubspec.yaml, and replace my main.dart file with the main.dart file you have in the example.

I've been trying to use your flutter_cast package for the past few days and no matter what I do, I keep running into this problem (the app only opens up for less then a second). 

`
D/bonsoir (  848): [46374] Bonsoir has found a service : name: google-nest-hub-344b48e0a9e4e23043077493f2667f7d, type: _googlecast._tcp., host: null, port: 0, txtRecord: 
D/bonsoir (  848): [46374] Bonsoir has resolved a service : name: google-nest-hub-344b48e0a9e4e23043077493f2667f7d, type: ._googlecast._tcp, host: /192.168.5.10, port: 8009, txtRecord: bs=FA8FCA6CD9C1	ca=231429#cd=00323286A13111F8D60F0BB151B68F2Dfn=Living Room displayic=/setup/icon.png#id=344b48e0a9e4e23043077493f2667f7dmd=Google Nest Hubnf=1rm=37C5B9293D983FBFrs=st=0ve=05
D/AndroidRuntime(  848): Shutting down VM
E/AndroidRuntime(  848): FATAL EXCEPTION: main
E/AndroidRuntime(  848): Process: com.example.test_cast, PID: 848
E/AndroidRuntime(  848): java.lang.IllegalStateException: entry.value must not be null
E/AndroidRuntime(  848): 	at fr.skyost.bonsoir.SuccessObject.getAttributes(SuccessObject.kt:62)
E/AndroidRuntime(  848): 	at fr.skyost.bonsoir.SuccessObject.serviceToJson(SuccessObject.kt:44)
E/AndroidRuntime(  848): 	at fr.skyost.bonsoir.SuccessObject.toJson(SuccessObject.kt:25)
E/AndroidRuntime(  848): 	at fr.skyost.bonsoir.discovery.BonsoirDiscoveryListener$onServiceResolved$1.run(BonsoirDiscoveryListener.kt:138)
E/AndroidRuntime(  848): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(  848): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(  848): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(  848): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
E/AndroidRuntime(  848): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(  848): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/AndroidRuntime(  848): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
W/OPDiagnose(  848): getService:OPDiagnoseService NULL
D/OSTracker(  848): OS Event: crash
I/flutter (  848): inside of the eventstream
D/AbstractTracker(  848): Event success
`

The error seems to only happen if I run the function CastDiscoveryService().search().
I tried even instantiating the CastDiscoveryService object, waiting a few seconds and then running the search function, but no luck there either.
After editing the plugin a little bit and adding some print statements inside of the search function, I have concluded that it barely even enters in the discovery.eventStream.listen
I know that it arrives to the Future.delayed(timeout) in the outside part. You can also see that my print statement "inside of the eventstream" gets printed out only AFTER the error occurs. Right after these messages, my app crashes on my phone and I just get an error saying Lost connection to device.

Occasionally after deleting the app I made, and doing flutter clean and flutter pub get, It works for a little while (it actually enters into the app). But even that doesn't always work.

Some details:
running flutter --version:
Flutter 2.5.0-6.0.pre.47 • channel master • https://github.com/flutter/flutter.git
Framework • revision 91f8b6be51 (2 hours ago) • 2021-08-11 00:37:54 -0700
Engine • revision 4fef55db10
Tools • Dart 2.14.0 (build 2.14.0-385.0.dev)

The phone I tried running it on is "OnePlus 3" running Android version 9.

**Comment by jonathantribouharet** [comment]
This error came from Bonsoir dependency https://github.com/jonathantribouharet/flutter_cast/issues/14
You need to use the git version of Bonsoir or wait they release the fix https://github.com/Skyost/Bonsoir/issues/17

**Comment by SirBepy** [comment]
Thank you!
I'd like to quickly confirm that it worked
Everything got fixed when I added the bonsoir dependency in the pubspec yaml like so

bonsoir:
    git:
      url: git://github.com/Skyost/Bonsoir.git
      path: bonsoir
