### ISSUE TITLE
Session getting closed by other devices

### ISSUE THREAD

**Issue by michelsahli** [jonathantribouharet/flutter_cast#26]
Hi Jonathan,

I'm currently experiencing a weird behavior. I'm connecting to a chromecast from my raspberry pi (which works). But once i'm connected with my phone and i disconnect from my phone, it also disconnect the raspberry pi.

I do not know the Google cast protocol very well, but could it be that the library does not verifiy if a close signal is meant for it or not?

Cheers,
Michel

**Comment by michelsahli** [comment]
Could it be a missing check in session.dart on the [line 77](https://github.com/jonathantribouharet/flutter_cast/blob/master/lib/session.dart#L77)?

```dart
77     } else if (message.namespace == kNamespaceConnection && message.payload['type'] == 'CLOSE') {
```

**Comment by jonathantribouharet** [comment]
It's the way you coded the receiver application, not related to this lib which is used for the sender application.
I think you should set the option `disableIdleTimeout` to `true` but not certain https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.CastReceiverOptions

But it's possible to close your phone without closing the app on the raspberry.
