### ISSUE TITLE
Could not get unknown property 'kotlin_version'/':mdns_plugin'.

### ISSUE THREAD

**Issue by pharshdev** [jonathantribouharet/flutter_cast#3]
```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/harsh/.pub-cache/hosted/pub.dartlang.org/mdns_plugin-1.1.4/android/build.gradle' line: 12

* What went wrong:
A problem occurred evaluating project ':mdns_plugin'.
> Could not get unknown property 'kotlin_version' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================
2: Task failed with an exception.
-----------
* Where:
Script '/Users/harsh/dev/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 324

* What went wrong:
A problem occurred configuring project ':mdns_plugin'.
> Could not get unknown property 'android' for project ':mdns_plugin' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

```

**Comment by jonathantribouharet** [comment]
Hi,
your problem is not related to this lib but more on your project configuration, I suggest you take a look on google / stackoverflow.

**Comment by puttanna** [comment]
C;losing is not a solution without suggesting a remedy. Inexperienced developers often get this error. I also searched for the same and found this link only to be told about some technicalities. Great!

**Comment by nathsagar24** [comment]
Totally there is only this link available for this issue and it also doesn't give any proper answer

**Comment by jonathantribouharet** [comment]
First link on Google I found is [](https://stackoverflow.com/questions/64834818/android-studio-could-not-get-unknown-property-kotlin-version) which seems to be the problem.

**Comment by nathsagar24** [comment]
> First link on Google I found is [https://stackoverflow.com/questions/64834818/android-studio-could-not-get-unknown-property-kotlin-version](https://stackoverflow.com/questions/64834818/android-studio-could-not-get-unknown-property-kotlin-version) which seems to be the problem.

I didn't have this issue and still I am getting the error

**Comment by diegoalex** [comment]
Hi Guys,

I got the same issue using dart_chromecast .
After spend few hours on it , I found out that just including 'kotlin_version' to my android/build.gradle fixed the issue .

`
buildscript {
    ext.kotlin_version= '1.4.10'
    repositories {
        google()
        jcenter()
        // Additional repository for fabric resources
        maven {
            url 'https://maven.fabric.io/public'
        }
    }
   ...
}
`
