### ISSUE TITLE
Recommended way of obtaining app ID

### ISSUE THREAD

**Issue by rmartinsfer** [jonathantribouharet/flutter_cast#32]
On the documentation we have an example on how to open youtube
  
```
session.sendMessage(CastSession.kNamespaceReceiver, {
    'type': 'LAUNCH',
    'appId': 'YouTube', // set the appId of your app here
  });
}
```
This works.
Now, I want to do the same to  Netflix, Amazon Prime and Disney.
My understanding is that I have to get the correct app ID for these apps, but I do not  know how to get the IDs.

**What is the best way to get the IDs?**

**Comment by jonathantribouharet** [comment]
Hello,
The appId are not public and the parameter used to launch theses apps also.
You may search on google or try to reverse engineering theirs apps.

**Comment by rmartinsfer** [comment]
I think I tried to approach the problem the wrong way, I'm just trying to connect to chromecast without trying to launch anything but I couldn't, I just want to stay connected to it, is there a way to do this?
