### ISSUE TITLE
How to play YouTube Video?

### ISSUE THREAD

**Issue by RaghuMudem** [jonathantribouharet/flutter_cast#4]
Sorry for asking information in issues place. I don't have any other way, so posting my query here.
I am successfully able to launch YouTube application in TV with chromecast using this library. And i can see the YouTube log screen in TV.

I would like to play a video in TV with my flutter app. Please suggest me what message i have to pass for playing YouTube video.

It would be very helpful, if you fill the code with some example YouTube video in the below logic of the library sample.

```
void _sendMessage(CastSession session) {
  session.sendMessage('urn:x-cast:namespace-of-the-app', {
    'type': 'sample',
  });
}
```

Thanks in advance.

**Comment by jonathantribouharet** [comment]
Hi, from what I could find on internet, for Youtube, the message type are "LOAD", "PLAY", "PAUSE".

I think you may be able to find whats exactly sent by use the debugger on Chrome and using the native cast feature of Chrome or you could use the javascript SDK on watch what is sent to the chromecast.

For "LOAD" you may try something like

```
  session.sendMessage('urn:x-cast:com.google.cast.media', {
    'type': 'LOAD',
   'videoId' : 'lwaJwaTyOB4'
  });
```

The namespace if probably wrong, I think `urn:x-cast:com.google.cast.media` is for playing MP4 URL, for Youtube you may try "urn:x-cast:com.google.youtube.mdx".

You may find some things by searching `urn:x-cast:com.google.youtube.mdx`:
- https://github.com/xat/castv2-youtube
- https://github.com/PierfrancescoSoffritti/android-youtube-player

When you find the solution, let me know I will put it in the README.

**Comment by RaghuMudem** [comment]
Hi @jonathantribouharet, 

Thanks for the reply. 
I have tried the given suggestions but didn't work for playing YouTube video. I am going through the source codes mentioned and other source codes available in internet.

I will update here in case of any positive result. If anyone has done playing YouTube from flutter, please post here in this thread. So that it will help for others.

**Comment by jefersonboesing** [comment]
Hi @RaghuMudem, did you manage to find out how to make this work?

**Comment by mohisham** [comment]
Any progress on this issue by anyone?

**Comment by jonathantribouharet** [comment]
Hi,
I tried to do this but it doesn't seem to work.

You can launch Youtube with

```
session.sendMessage(CastSession.kNamespaceReceiver, {
  'type': 'LAUNCH',
  'appId': 'YouTube',
});
```

But the part for playing the video doesn't work, maybe related to #6 
I found 2 different code

```
session.sendMessage(CastSession.kNamespaceMedia, {
  'type': 'PLAY',
  'autoPlay': true,
  'currentTime': 0,
  'media': {
    'contentId': 'JmQk4Yp9bww',
    'contentType': 'x-youtube/video',
    'streamType': 'BUFFERED',
  }
});
```

```
session.sendMessage('urn:x-cast:com.google.youtube.mdx', {
 'type': 'flingVideo',
  'data': {
    'currentTime': 0,
    'videoId': 'JmQk4Yp9bww',
  }
});
```

This library was made to use custom protocol, maybe there is a problem with the `sendMessage` function, like the `requestId`.

**Comment by murilosamuel** [comment]
someone managed to play a video on youtube?

**Comment by jonathantribouharet** [comment]
After some research, I found it's very difficult to play a video on Youtube since it requires to have a "session id", mostly coming from your web browser... This is far beyond the scope of this lib.

**Comment by hanan0007** [comment]
using webview , extract the video id with javascript , and then pass this to the youtube explode package , it will give you the stream url , then pass it to the chrome cast , with mp4 metadata
