### ISSUE TITLE
Play video

### ISSUE THREAD

**Issue by CodeDruid13** [jonathantribouharet/flutter_cast#6]
Hello, how would i send a video link to play on the cast device? For video i think it's 
`urn:x-cast:com.google.cast.media`  but am not sure how to approach this. I have the video link as an Mp4

**Comment by Cdriic** [comment]
> Hello, how would i send a video link to play on the cast device? For video i think it's
> `urn:x-cast:com.google.cast.media` but am not sure how to approach this. I have the video link as an Mp4

Hello,
Yes it's "urn:x-cast:com.google.cast.media".

Normally it should be this:
`session.sendMessage(CastSession.kNamespaceMedia, {
      'type': 'LOAD',
      'autoPlay': true,
      'currentTime': 0,
      'activeTracks': [],
      'media': {
        'contentId': "https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_20MB.mp4",
        'contentType': "video/mp4",
        'images': images,
        'title': "Big Buck Bunny",
        'streamType': 'BUFFERED',
      });`

but it does not work.

**Comment by murilosamuel** [comment]
Someone managed to play a video on youtube?

**Comment by Joyker** [comment]
Hello, is there any solution ?

**Comment by jonathantribouharet** [comment]
Hi,
the example has been updated to let you play a video, but it's by using the application of someone else.
You cannot directly play a mp4 without an application.
