### ISSUE TITLE
startDiscovery: enableUpdating is currently ignored on the Android platform

### ISSUE THREAD

**Issue by zilvinas-t** [jonathantribouharet/flutter_cast#9]
Hello,

I was trying to get cast device list and received an error: 
**startDiscovery: enableUpdating is currently ignored on the Android platform**

**Comment by jonathantribouharet** [comment]
Hello,
From https://pub.dev/packages/mdns_plugin

> One limitation is that on Android, the enableUpdating flag is currently ignored. Future work will correct this to bring the platforms in parity.
